version: '3.8'

services:

  mysql:
    image: mysql:5.7.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: balflex
      MYSQL_USER: sab
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      
  apache:
    container_name: php-apache
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
        - mysql
    volumes:
        - ./phppagina/src:/var/www/html/
    ports:
      - 8000:80
      
  